### ISSUE TITLE
Drehimpulsoperator Seite. 7

### ISSUE THREAD

**Issue by niklasneubrand** [BigThonkers/LaTeX-Mitschriebe-Semester-4#13]
Anstatt der Matrix müsste da die Determinante stehen. Vgl. https://de.wikipedia.org/wiki/Kreuzprodukt#Komponentenweise_Berechnung

**Comment by benjaminbutton13659** [comment]
Danke für die Info ich schaue es mir gleich an. Wäre nett wenn du schreiben könntest welches Skript auf Seite 7 du meinst.

**Comment by benjaminbutton13659** [comment]
okey habs gefunden und korrigiert. Danke für die Mitarbeit an unserem Projekt!
